#!/usr/bin/env bash
openssl genrsa -out ca/ca.key 1024
openssl req -new -x509 -days 3650 -extensions v3_ca -keyout ca/cakey.pem -out ca/cacert.pem -nodes -subj "/C=US/ST=STATE/L=CITY/O=ORG/CN=caching_proxy/"
echo \"02\" > ca/cacert.srl